// @refresh reload
import { Suspense } from "solid-js";
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Link,
  Meta,
  Routes,
  Scripts,
  Title,
} from "solid-start";
import GoogleAnalytics from "./components/GoogleAnalytics";
import "./root.css";

export default function Root() {
  return (
    <Html lang="en">
      <Head>
        <Meta name="description" content="Generated by create-jd-app" />
        <Title>Eric Minassian - Software Engineer</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="theme-color" content="#FFFFFF" />
        <Meta
          name="description"
          content="Portfolio of Eric Minassian, a Computer Science & Finance student at UC Irvine, showcasing his skills and projects."
        />
        <Meta name="author" content="Eric Minassian" />
        <Meta
          name="keywords"
          content="eric minassian, software engineer, finance, portfolio, internship, university of california, irvine, uci, computer science, business administration, resume, linkedin, github"
        />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <GoogleAnalytics />
      <Body>
        <Suspense>
          <ErrorBoundary>
            <Routes>
              <FileRoutes />
            </Routes>
          </ErrorBoundary>
        </Suspense>
        <Scripts />
      </Body>
    </Html>
  );
}
